---
 - hosts: all
   ignore_errors: yes
   become: yes
   tasks:
  
    - name: update server
      yum: 
        name: "*"
        state: latest
        when: ansible_distribution == "CentOS"

    - name: upgrade server
      apt: 
        name: "*"
        state: latest
        when: ansible_distribution  == "Ubuntu"

    - name: Install tree
      yum:
        name: tree
        state: present
      when: ansible_distribution == "CentOS"

    - name: Install tree
      apt: 
        name: tree
        state: present
      when: ansible_distribution  == "Ubuntu"
